---
swagger: "2.0"
info:
  description: "AI Photo Search application, built during the Cloud and Big Data course\
    \ at Columbia University."
  version: "1.0.0"
  title: "AI Photo Search"
#host: "267q6olw0h.execute-api.us-east-1.amazonaws.com"
basePath: "/v2"
schemes:
- "https"
paths:
  /search:
    get:
      operationId: "searchPhotos"
      produces:
      - "application/json"
      parameters:
      - name: "q"
        in: "query"
        required: false
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/SearchResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "500":
          description: "500 response"
          schema:
            $ref: "#/definitions/Error"
        "403":
          description: "403 response"
          schema:
            $ref: "#/definitions/Error"
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        httpMethod: post
        type: aws_proxy
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${searchphotos.Arn}/invocations
    options:
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "SearchResponse"
        required: true
        schema:
          $ref: "#/definitions/SearchResponse"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /upload/{bucket}/{object}:
    put:
      operationId: "uploadPhoto"
      produces:
      - "application/json"
      parameters:
      - name: "Content-Type"
        in: "header"
        required: true
        type: "string"
      - name: "x-amz-meta-customLabels"
        in: "header"
        required: true
        type: "string"
      - name: "object"
        in: "path"
        required: true
        type: "string"
      - name: "bucket"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/MODEL81531f"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "500":
          description: "500 response"
          schema:
            $ref: "#/definitions/Error"
        "403":
          description: "403 response"
          schema:
            $ref: "#/definitions/Error"
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        httpMethod: "PUT"
        type: "aws"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:s3:path/${bucket}/${object}"
        requestParameters:
          integration.request.header.Content-Type: "method.request.header.Content-Type"
          integration.request.header.x-amz-meta-customLabels: "method.request.header.x-amz-meta-customLabels"
          integration.request.path.bucket: "method.request.path.bucket"
          integration.request.path.object: "method.request.path.object"
    options:
      consumes:
      - "application/json"
      parameters:
      - name: "bucket"
        in: "path"
        required: true
        type: "string"
      - name: "object"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  MODEL81531f:
    type: "object"
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
  Photo:
    type: "object"
    properties:
      url:
        type: "string"
      labels:
        type: "array"
        items:
          type: "string"
  SearchResponse:
    type: "object"
    properties:
      results:
        type: "array"
        items:
          $ref: "#/definitions/Photo"
